home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('daftar', views.daftar, name='daftarr'),
    path('peserta/<int:pk_id>/', views.pesertaku, name='pesertaa'),
    path('delete/<int:del_id>/', views.delete, name = "delete"),
    path('deletepeserta/<int:id_del>/', views.deletepeserta, name = "deletepsrt"),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

home/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    nama_kegiatan = models.CharField('Nama Kegiatan', max_length = 30) 

    def __str__(self): 
        return self.nama_kegiatan


class Peserta(models.Model):
    nama_peserta = models.CharField('Nama Peserta', max_length = 30)
    kegiatann = models.ForeignKey(Kegiatan, on_delete=models.CASCADE , null=True, blank=True)

    def __str__(self):
        return self.nama_peserta

home/forms.py
from django import forms
from .models import Kegiatan, Peserta


class Form_Kegiatan(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = ('nama_kegiatan', )


class Form_Peserta(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = ('nama_peserta', )

home/views.py
from django.shortcuts import render, redirect
from .forms import Form_Kegiatan, Form_Peserta
from .models import Kegiatan, Peserta
# Create your views here.


def index(request):
    
    if request.method == 'POST':
        isikegiatan = Form_Kegiatan(request.POST)
        if isikegiatan.is_valid():
            isikegiatan.save()
    isikegiatan = Form_Kegiatan()


    context= {"kegiatan": isikegiatan,}
    return render(request, 'index.html', context)

def pesertaku(request, pk_id):
    if request.method == 'POST':
        isipeserta = Form_Peserta(request.POST)
        if isipeserta.is_valid():
            peserta = Peserta(kegiatann = Kegiatan.objects.get(id=pk_id),
                nama_peserta = isipeserta.data['nama_peserta'])
            peserta.save()
            return redirect('home:index')
    isipeserta = Form_Peserta()
    context = {"peserta": isipeserta, }
    return render(request, 'isiorang.html', context)
    

def delete(request, del_id) :
    Kegiatan.objects.filter(id= del_id).delete()
    return redirect('home:daftarr') 


def deletepeserta(request, id_del):
    Peserta.objects.filter(id= id_del).delete()
    return redirect('home:daftarr')

def daftar(request):
    isipeserta = Form_Peserta()
    value = Kegiatan.objects.all()
    isikegiatan = Form_Kegiatan()
    psrt = Peserta.objects.all()
    
    context = {"peserta": isipeserta, "kegiatan": isikegiatan, "value":value, "psrt":psrt }
    return render(request, 'daftar.html', context)

home/templates/daftar.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

    <link href='https://fonts.googleapis.com/css?family=Averia Libre' rel='stylesheet'>
    <body>
    {%for i in value%}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{i.nama_kegiatan}}</h5>
            {% for x in psrt %}
            {% if x.kegiatann == i %}
            <p class="card-text">{{ x.nama_peserta }}</p>
            <a href="{%url 'home:deletepsrt' x.id%}" class="card-link">hapus peserta</a>
            {% endif %}
            {% endfor %}
            <a href="{%url 'home:pesertaa' pk_id=i.pk%}" class="card-link">peserta</a>
                <a href="{% url 'home:index' %}" class="card-link">kegiatan</a>
                <a href="{%url 'home:delete' i.id%}" class="card-link">hapus</a>
            </div>
        </div>
        {% endfor %}
    </body>
</html>

home/templates/index.html
<html>
    <h1>Hello WORD</h1>
    
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ kegiatan.as_p }}<br>
        <button class="btn btn-primary" role="button" type="submit">Save</button>
    </form>
    <a href="{% url 'home:daftarr' %}">ke daftar</a>
</html>

home/templates/isiorang.html
<html>
<form method="POST" class="post-form">
    {% csrf_token %}
    {{ peserta.as_p }}
    <button class="btn btn-primary" role="button" type="submit">Save</button>
</form>

</html>